---
title: "Lab 11 Problem 3"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
runtime: shiny
---

```{r global}
library(flexdashboard)
library(datasets)
library(shiny)
library(tidyverse)
data(faithful)
```

Column
-------------------

### Chart 3a

```{r}
server <- function(input, output) {
  output$main_plot <- renderPlot({
    if(input$density) {
      if(input$individual_obs) {
        ggplot(faithful, aes(x = eruptions)) +
          geom_histogram(bins = as.numeric(input$n_breaks),
                         aes(x = eruptions, stat(density))) +
          labs(
            title = "Geyser eruption duration",
            x = "Duration (minutes)"
            ) +
          geom_rug() +
          geom_density(adjust = input$bw_adjust, color = "blue")
      } else {
        ggplot(faithful, aes(x = eruptions)) +
          geom_histogram(bins = as.numeric(input$n_breaks),
                         aes(x = eruptions, stat(density))) +
          labs(
            title = "Geyser eruption duration",
            x = "Duration (minutes)"
            ) +
          geom_density(adjust = input$bw_adjust, color = "blue")
      }
    } else {
      if(input$individual_obs) {
        ggplot(faithful, aes(x = eruptions)) +
          geom_histogram(bins = as.numeric(input$n_breaks),
                         aes(x = eruptions, stat(density))) +
          labs(
            title = "Geyser eruption duration",
            x = "Duration (minutes)"
            ) +
          geom_rug()
      } else {
        ggplot(faithful, aes(x = eruptions)) +
          geom_histogram(bins = as.numeric(input$n_breaks),
                         aes(x = eruptions, stat(density))) +
          labs(
            title = "Geyser eruption duration",
            x = "Duration (minutes)"
            )
      }
    }
  })
}
ui <- bootstrapPage(

  selectInput(inputId = "n_breaks",
      label = "Number of bins in histogram (approximate):",
      choices = c(10, 20, 35, 50),
      selected = 20),

  checkboxInput(inputId = "individual_obs",
      label = strong("Show individual observations"),
      value = FALSE),

  checkboxInput(inputId = "density",
      label = strong("Show density estimate"),
      value = FALSE),

  plotOutput(outputId = "main_plot", height = "300px"),

  # Display this only if the density is shown
  conditionalPanel(condition = "input.density == true",
    sliderInput(inputId = "bw_adjust",
        label = "Bandwidth adjustment:",
        min = 0.2, max = 2, value = 1, step = 0.2)
  )

)

shinyApp(ui = ui, server = server)
```

Column
---------------

### Chart 3b(1)

```{r}
server <- function(input, output) {
  output$main_plot <- renderPlot({
    if(input$trend_line) {
      if(input$error_bars) {
        ggplot(faithful, aes(x = waiting, y = eruptions)) +
        geom_point(size = input$pt_size) +
        labs(
          title = "Eruption Time versus Waiting Time",
          x = "Waiting Time (minutes)",
          y = "Eruption Time"
        ) +
        geom_smooth(method = "lm", se = TRUE)
      } else {
        ggplot(faithful, aes(x = waiting, y = eruptions)) +
        geom_point(size = input$pt_size) +
        labs(
          title = "Eruption Time versus Waiting Time",
          x = "Waiting Time (minutes)",
          y = "Eruption Time"
        ) +
        geom_smooth(method = "lm", se = FALSE)
      }
    } else {
      ggplot(faithful, aes(x = waiting, y = eruptions)) +
        geom_point(size = input$pt_size) +
        labs(
          title = "Eruption Time versus Waiting Time",
          x = "Waiting Time (minutes)",
          y = "Eruption Time"
        )
    }
  })
}
ui <- bootstrapPage(
  checkboxInput(inputId = "trend_line",
                label = strong("Include trend line"),
                value = FALSE),
  sliderInput(inputId = "pt_size",
              label = "Point size",
              min = 0.2, max = 2, value = 1, step = 0.2),
  plotOutput(outputId = "main_plot", height = "300px"),
  conditionalPanel(condition = "input.trend_line == true",
                   checkboxInput(inputId = "error_bars",
                                 label = strong("Include error bars"),
                                 value = FALSE)
                   )
)
shinyApp(ui = ui, server = server)
```

### Chart 3b(2)

